vim.keymap.set("n", "<Leader>a", function() require("harpoon.mark").add_file() end)
vim.keymap.set("n", "<Leader>o", function() require("harpoon.ui").toggle_quick_menu() end)
vim.keymap.set("n", "<Leader>&", function() require("harpoon.ui").nav_file(1) end)
vim.keymap.set("n", "<Leader>é", function() require("harpoon.ui").nav_file(2) end)
vim.keymap.set("n", "<Leader>\"", function() require("harpoon.ui").nav_file(3) end)
vim.keymap.set("n", "<Leader>'", function() require("harpoon.ui").nav_file(4) end)
